FROM python:3.11-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV INSIDE_A_DOCKER Yes

COPY store_backend/requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY store_backend/docker-entrypoint.sh /app/
RUN chmod +x /app/docker-entrypoint.sh
COPY store_backend/. /app/

COPY .env /

EXPOSE 8000
CMD ["/app/docker-entrypoint.sh"]
