FROM python:3.11-alpine

WORKDIR /app

RUN apk --no-cache add \
    build-base \
    freetype-dev \
    fribidi-dev \
    harfbuzz-dev \
    jpeg-dev \
    lcms2-dev \
    libimagequant-dev \
    openjpeg-dev \
    tcl-dev \
    tiff-dev \
    tk-dev \
    zlib-dev

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV INSIDE_A_DOCKER Yes

COPY store_backend/requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install django-cors-headers

COPY .env /

COPY store_backend/docker-entrypoint.sh /app/
RUN chmod +x /app/docker-entrypoint.sh
COPY store_backend/. /app/

EXPOSE 8000
CMD ["/app/docker-entrypoint.sh"]
