# Generated by Django 4.1.4 on 2023-01-12 14:48

from django.db import migrations, models


def update_item_sku(apps, schema_editor):
    item = apps.get_model('main', 'Item')
    for item in item.objects.all():
        item.sku = item.slug
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_alternate_title_item_dimensions_and_more'),
    ]

    operations = [
        migrations.RunPython(update_item_sku, reverse_code=migrations.RunPython.noop),

        migrations.AlterField(
            model_name='item',
            name='dimensions',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='minifigures_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='parts_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='series',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
