# Generated by Django 4.1.4 on 2023-01-12 15:11

from django.db import migrations, models


def update_item_sku(apps, schema_editor):
    item = apps.get_model('main', 'Item')
    for item in item.objects.all():
        item.sku = item.slug
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_alternate_title_item_dimensions_and_more'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE'),
        migrations.RunPython(update_item_sku, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RunSQL(migrations.RunSQL.noop, reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
