# Generated by Django 4.1.4 on 2023-01-12 15:59

from django.db import migrations, models
import uuid


def update_order_unique_uuid(apps, schema_editor):
    order = apps.get_model('main', 'Order')
    for order in order.objects.all():
        order.unique_uuid = uuid.uuid4()
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_description_alter_item_sku'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE'),
        migrations.RunPython(update_order_unique_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='unique_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunSQL(migrations.RunSQL.noop, reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
