# Generated by Django 4.1.4 on 2023-01-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_unique_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegoSetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lego_sets/')),
                ('ordering', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Изображение набора',
                'verbose_name_plural': 'Изображения наборов',
                'ordering': ['ordering'],
            },
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='LegoSet',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderLegoSet',
        ),
        migrations.AlterModelOptions(
            name='legoset',
            options={'verbose_name': 'Набор', 'verbose_name_plural': 'Наборы'},
        ),
        migrations.AlterModelOptions(
            name='orderlegoset',
            options={'verbose_name': 'Набор в заказе', 'verbose_name_plural': 'Наборы в заказе'},
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
        migrations.AddField(
            model_name='legosetimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.legoset'),
        ),
        migrations.AlterUniqueTogether(
            name='legosetimage',
            unique_together={('item', 'ordering')},
        ),
    ]
