# Generated by Django 4.1.4 on 2023-01-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_legosetimage_rename_orderitem_orderlegoset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minifigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('alternate_title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('quantity_in_stock', models.IntegerField()),
                ('quantity_sold', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('series', models.CharField(blank=True, max_length=100)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Минифигурка',
                'verbose_name_plural': 'Минифигурки',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('alternate_title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('quantity_in_stock', models.IntegerField()),
                ('quantity_sold', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
            },
        ),
        migrations.AlterField(
            model_name='legosetimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ordering', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.part')),
            ],
            options={
                'verbose_name': 'Изображение детали',
                'verbose_name_plural': 'Изображения деталей',
                'ordering': ['ordering'],
                'unique_together': {('item', 'ordering')},
            },
        ),
        migrations.CreateModel(
            name='MinifigureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('ordering', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.minifigure')),
            ],
            options={
                'verbose_name': 'Изображение минифигурки',
                'verbose_name_plural': 'Изображения минифигурок',
                'ordering': ['ordering'],
                'unique_together': {('item', 'ordering')},
            },
        ),
    ]
