# Generated by Django 4.1.4 on 2022-12-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_orderitem_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_id',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
