# Generated by Django 4.1.4 on 2023-01-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
    ]
