# Generated by Django 4.1.4 on 2023-01-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
