# Generated by Django 4.1.4 on 2023-01-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_order_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.IntegerField(default=0),
        ),
    ]
