# Generated by Django 4.1.4 on 2023-01-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_order_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderId',
        ),
        migrations.AlterField(
            model_name='order',
            name='middle_name',
            field=models.CharField(max_length=50),
        ),
    ]
