# Generated by Django 4.1.4 on 2023-01-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_order_orderid_alter_order_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
