# Generated by Django 4.1.4 on 2023-02-01 09:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_order_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_quantities',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items_slugs',
        ),
        migrations.AddField(
            model_name='order',
            name='items_legoSets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AddField(
            model_name='order',
            name='items_minifigures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AddField(
            model_name='order',
            name='items_parts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('spb', 'Курьером по СПб'), ('pochta', 'Почтой России'), ('SDEK', 'СДЭК')], max_length=100),
        ),
    ]
